#!/bin/bash
clear

echo "====================================="
echo "        INICIANDO SLOWDNS"
echo "====================================="

fun_bar() {
    (
        $1 > /dev/null 2>&1
        touch $HOME/fim
    ) &

    tput civis
    echo -ne "  ESPERANDO ["
    while true; do
        for((i=0; i<18; i++)); do
            echo -ne "#"
            sleep 0.1
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -ne "]"
        sleep 1
        tput cuu1
        tput dl1
        echo -ne "  ESPERANDO ["
    done
    echo -e "] OK"
    tput cnorm
}

fun_start() {

    # Verificar si ya está corriendo
    if pgrep -f dns-server > /dev/null; then
        echo "SlowDNS ya está en ejecución."
        exit 0
    fi

    cd /etc/slowdns || exit 1

    screen -dmS slowdns ./dns-server -udp :5300 \
    -privkey-file /root/server.key \
    1234 127.0.0.1:22
}

fun_bar fun_start

echo ""
echo "✔ SlowDNS iniciado correctamente"
echo ""
read -p "Presiona ENTER para continuar..."

slowdns