#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mESPERA \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mESPERA \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput bold ; printf '%40s%s%-12s\n' "INSTALANDO SERVICIO PERSONALIZADO SLOWDNS" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "      Este script instalará"
echo -e " SlowDNS para túnel DNS con Servicio Personalizado."
echo -e ""
echo -e "         \033[1;33mInstalador Mod VpsPack \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "ACTUALIZANDO LISTA DE PAQUETES..."

fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'

echo -e "INSTALANDO Y ACTUALIZANDO PAQUETES NECESARIOS..."

install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'

echo -e "CONFIGURANDO IPTABLES..."

ipt_set () {
cd /etc
mv rc.local rc.local.bkp
wget https://github.com/powermx/dnstt/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'

clear
echo ""
echo -e "\033[1;31m ¡ATENCIÓN EN ESTA ETAPA! \033[1;33m"
echo ""
echo -ne "\033[1;32m INGRESA TU NS (NAMESERVER)\033[1;37m: "; read nameserver

cd /etc/slowdns
touch infons
echo $nameserver > infons
sleep 1

echo ""
echo -ne "\033[1;32m INGRESA EL PUERTO DEL SERVICIO A USAR CON SLOWDNS (NO 53/5300)\033[1;37m: "
read customservice

if [[ "$customservice" == "53" || "$customservice" == "5300" ]]; then
    echo -e "\033[1;31m ERROR: El puerto no puede ser 53 ni 5300. \033[0m"
    exit 1
fi

cat <<EOF > /etc/slowdns/startdns
#!/bin/bash
echo "INICIANDO SLOWDNS"
screen -dmS slowdns$customservice /etc/slowdns/dns-server -udp :5300 -privkey-file /root/server.key $nameserver 127.0.0.1:$customservice
echo ""
echo "       ¡SLOWDNS INICIADO CORRECTAMENTE!"
EOF

cat <<EOF > /etc/slowdns/restartdns
#!/bin/bash
echo "REINICIANDO SLOWDNS"
screen -ls | grep slowdns | cut -d. -f1 | awk '{print \$1}' | xargs kill
screen -dmS slowdns$customservice /etc/slowdns/dns-server -udp :5300 -privkey-file /root/server.key $nameserver 127.0.0.1:$customservice
echo ""
echo "¡SlowDNS Reiniciado Correctamente! [✔]"
EOF

set_ns () {
chmod +x /etc/slowdns/startdns
chmod +x /etc/slowdns/restartdns
cp /etc/slowdns/startdns /bin/
cp /etc/slowdns/restartdns /bin/
}
fun_bar 'set_ns'

echo ""
echo "Verificando existencia de clave..."
sleep 2
echo ""
echo "      Por favor espera...  "
sleep 2

cd
key1="/root/server.key"
key2="/root/server.pub"

if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "¡Archivo de clave encontrado!"
sleep 1
echo ""

echo -e "\033[1;31m INSTALACIÓN COMPLETADA!\033[0m"
echo ""
echo -ne "\033[1;33mTU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU CLAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m TU CLAVE está guardada en /root/server.pub\033[0m"
echo -e "\033[1;33mGuárdala en un lugar seguro, puede que la necesites en el futuro.\033[0m"
echo ""
read -p "Presiona [Enter] para volver al menú o CTRL+C para salir"
slowdns

else

echo -e "No se encontraron claves, generando nuevas..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub

iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns

clear
echo -e "\033[1;31m INSTALACIÓN COMPLETADA!\033[0m"
echo ""
echo -ne "\033[1;33mTU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU CLAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m TU CLAVE está guardada en /root/server.pub\033[0m"
echo -e "\033[1;33mGuárdala en un lugar seguro.\033[0m"
echo ""
read -p "Presiona [Enter] para volver al menú o CTRL+C para salir"
slowdns

fi